title: NoÃ© Lallouet
email: noe.lallouet@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Machine Learning Engineer specialising in Deep Reinforcement Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://noual.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-feed
  - jekyll-seo-tag
